SELECT NAME, PROJECTS_COUNT
FROM (
SELECT NAME, COUNT(CLIENT_ID) AS PROJECTS_COUNT
FROM client
JOIN project ON client.ID = project.CLIENT_ID
GROUP BY NAME) AS count_table
WHERE PROJECTS_COUNT = (
SELECT MAX(PROJECTS_COUNT)
FROM (
SELECT NAME, COUNT(CLIENT_ID) AS PROJECTS_COUNT
FROM client
JOIN project ON client.ID = project.CLIENT_ID
GROUP BY NAME) AS count_table2
)