-- Creating 'worker' table
CREATE TABLE worker (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(1000) NOT NULL CHECK(LENGNAME TH(NAME) >= 2),
    BIRTHDAY DATE CHECK(EXTRACT(YEAR FROM BIRTHDAY) > 1900),
    LEVEL VARCHAR(100) NOT NULL CHECK(LEVEL IN ('Trainee', 	'Junior', 'Middle', 'Senior')),
    SALARY INT CHECK(SALARY >= 100 AND SALARY <= 100000)
);

-- Creating 'client' table
CREATE TABLE client (
     ID INT AUTO_INCREMENT PRIMARY KEY,
     NAME VARCHAR(1000) NOT NULL CHECK(LENGTH(NAME) >= 2)
);	
 

-- Creating 'project' table
CREATE TABLE project (
     ID INT  AUTO_INCREMENT PRIMARY KEY,
     CLIENT_ID INT,
     START_DATE DATE,
     FINISH_DATE DATE
);

-- Creating 'project_worker' table
CREATE TABLE project_worker (
    PROJECT_ID INT,
    WORKER_ID INT,
    PRIMARY KEY(PROJECT_ID, WORKER_ID),
    FOREIGN KEY(PROJECT_ID) REFERENCES project(ID),
    FOREIGN KEY(WORKER_ID) REFERENCES worker(ID)
);